data-access:
  mode: explicit-files
  files: 
    - /depot/cms/users/dkondra/90322FC2-4027-0E47-92E4-22307EC8EAD2.root

executor:
  backend: dask-gateway
  # backend: dask-local
  # backend: sequential
  n_workers: 1

processor:
  parallelize_over: columns
  columns:
    method: collections
    values: [Muon]
  load_columns_into_memory: True
  worker_operation_time: 0
