data-access:
  mode: dbs-datasets
  xrootdserver: cms-xcache.rcac.purdue.edu:1094
  datasets:
      - /SingleMuon/Run2016B-02Apr2020_ver2-v1/NANOAOD
      - /SingleMuon/Run2016C-02Apr2020_ver2-v1/NANOAOD
executor:
  backend: futures
processor:
  parallelize_over: files
  collections:
      - Muon
  load_columns_into_memory: True
  worker_operation_time: 0
