executor:
  backend: futures
data-access:
  mode: dbs-dataset
#  xrootdserver: eos.cms.rcac.purdue.edu:1094
  xrootdserver: cms-xcache.rcac.purdue.edu:1094
  datasets:
      - /SingleMuon/Run2016B-02Apr2020_ver2-v1/NANOAOD
processor:
  parallelize_over: files
  columns: 1
  operation: nothing
