executor:
  backend: futures
data-access:
  mode: local_dirs
  directories:
      - /eos/purdue/store/data/Run2016B/SingleMuon/NANOAOD/02Apr2020_ver2-v1/20000/
processor:
  parallelize_over: files
  columns:
    - event
  operation: sum
