data-access:
  mode: explicit-files
  files: 
    - tests/data/nano_dimuon.root
executor:
  backend: sequential
processor:
  parallelize_over: files
  collections:
      - Muon
  load_columns_into_memory: True
  worker_operation_time: 1

