executor:
  backend: sequential
data-access:
  mode: dbs_dataset
#  xrootdserver: eos.cms.rcac.purdue.edu:1094
  xrootdserver: cms-xcache.rcac.purdue.edu:1094
  dataset: /SingleMuon/Run2016B-02Apr2020_ver2-v1/NANOAOD
processor:
  parallelize_over: files
  columns: 5
  operation: sum
