data-access:
  mode: dbs-files
  # xrootdserver: eos.cms.rcac.purdue.edu:1094
  # xrootdserver: cmsxrootd.hep.wisc.edu:1094
  xrootdserver: cms-xcache.rcac.purdue.edu:1094
  files:
      - /store/data/Run2016B/SingleMuon/NANOAOD/02Apr2020_ver2-v1/20000/90322FC2-4027-0E47-92E4-22307EC8EAD2.root       
executor:
  backend: futures
processor:
  parallelize_over: files
  collections:
      - Muon
  load_columns_into_memory: True
  worker_operation_time: 0
