data-access:
  mode: explicit-files
  files: 
    - tests/data/nano_dimuon.root
executor:
  backend: sequential
processor:
  parallelize_over: files
  collections:
      - Muon
  operation: load_into_memory
