executor:
  backend: sequential
  # backend: futures
  # backend: dask-local
  # backend: dask-gateway
data-access:
  mode: local
  files: 
    - tests/data/nano_dimuon.root
  # mode: local_dirs
  # directories:
  #     - /home/dkondra/depot/users/dkondra/af-benchmark/tests/data/
processor:
  parallelize_over: files
  # parallelize_over: columns
  method: uproot
  # method: nanoevents
  columns: 5
    # - event
    # - Muon_pt
    # - Muon_eta
  operation: sum
