engine:
  backend: sequential
  # backend: dask-gateway
data-access:
  mode: local
  files: 
    - tests/data/nano_dimuon.root
processing:
  method: nanoevents
  columns:
    - event
    - Muon_pt
  operation: mean
  write: false
measurements:
  what:
    - timing
    - ram
  report:
    - print
